
-- Clear all data from the tables for a fresh migration
TRUNCATE TABLE
    public.bert_models,
    public.country,
    public.intervention,
    public.oewg_ngram_filter_phrases,
    public.oewg_ngrams_to_use,
    public.oewg_ngram_statistics,
    public.oewg_ngram_community_frequencies,
    public.oewg_ngram_cluster_from_shared_sentences,
    public.user_settings,
    public.bert_topic_definition,
    public.oewg_topics,
    public.speech_sentence,
    public.wic_fellow_attendance_record,
    public.intervention_cleaned_words,
    public.intervention_photo,
    public.intervention_alternative_gender_source,
    public.analysis_ngram_community_stats,
    public.oewg_ngram_usefulness_ai_rating,
    public.analysis_ngram_clustering_silhouette_by_sentence,
    public.bert_speaker_pairwise_distance,
    public.oewg_ngrams_to_topic_names,
    public.analysis_ai_labelled_topic_community_stats,
    public.sentence_topic_ai_classification_pivoted,
    public.junc_sentence_id_to_ngram_id,
    public.analysis_bert_labelled_topic_community_stats,
    public.bert_speaker_avg_topic_probability,
    public.bert_topic_keywords,
    public.oewg_ngram_sentence_samples,
    public.sentence_topic_ai_classification_unpivoted,
    public.bert_sentence_topic_probabilities
RESTART IDENTITY CASCADE;
