// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsluzynpsbpkoszhycsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbHV6eW5wc2Jwa29zemh5Y3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTY5NTEsImV4cCI6MjA2NTU5Mjk1MX0.raSFHnD0cfYuya2VGiSY4L-Ogcw8DSQGMAVtP8LiLIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);